name: Deploy Next.js to EC2 (Build on Actions)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract PR number from merge commit
        id: pr_number
        run: |
          # Get the merge commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Extract PR number from merge commit message
          PR_NUMBER=$(echo "$COMMIT_MSG" | grep -oP '(?<=Merge pull request #)\d+' || true)

          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found in commit message (might be a direct push)"
            echo "pr_found=false" >> $GITHUB_OUTPUT
          else
            echo "Found PR number: $PR_NUMBER"
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "pr_found=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Comment PR - Deployment Started
        if: steps.pr_number.outputs.pr_found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.pr_number.outputs.pr_number }};
            const workflow_url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `## 🚀 Deployment Started\n\n` +
                    `The deployment for this PR has been initiated.\n\n` +
                    `**Status:** In Progress ⏳\n` +
                    `**Workflow:** [View deployment progress](${workflow_url})\n` +
                    `**Started at:** ${new Date().toISOString()}\n\n` +
                    `I'll update this comment once the deployment completes.`
            });

      - name: Prepare deployment package
        run: |
          mkdir -p deployment_package

          echo "Copying .next directory..."
          cp -R .next deployment_package/

          echo "Checking for public directory..."
          if [ -d "public" ]; then
            echo "'public' directory found. Copying..."
            cp -R public deployment_package/
          else
            echo "Warning: 'public' directory not found. Skipping copy."
          fi

          echo "Copying package.json..."
          cp package.json deployment_package/

          echo "Copying pnpm-lock.yaml..."
          cp pnpm-lock.yaml deployment_package/

          echo "Checking for next.config.mjs file..."
          if [ -f "next.config.mjs" ]; then
            echo "'next.config.mjs' file found. Copying..."
            cp next.config.mjs deployment_package/
          else
            echo "Warning: 'next.config.mjs' file not found. Skipping copy."
          fi

          echo "Contents of deployment_package:"
          ls -la deployment_package/

      - name: Validate deployment prerequisites
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Validate required environment
            if [ ! -d "${{ secrets.EC2_TARGET }}" ]; then
              echo "Error: Target directory ${{ secrets.EC2_TARGET }} does not exist"
              exit 1
            fi

            # Check if Node.js environment is available
            [ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"
            if ! command -v node >/dev/null 2>&1; then
              echo "Error: Node.js is not available"
              exit 1
            fi

            echo "Prerequisites validated successfully"

      - name: Deploy to EC2 via SSH and rsync
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: 'deployment_package/*'
          TARGET: ${{ secrets.EC2_TARGET }}
          ARGS: '-avz --delete'

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_TARGET }}

            # Source environment for Node.js and PM2
            export PATH="$HOME/.nvm/versions/node/$(nvm current)/bin:$PATH"
            [ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"
            [ -s "$HOME/.bashrc" ] && source "$HOME/.bashrc"

            # Verify Node.js and PM2 are available
            echo "Node.js version: $(node --version)"
            echo "PM2 version: $(pm2 --version)"

            # Install production dependencies
            if [ -n "${{ secrets.ENV_FILE_PRODUCTION }}" ]; then
              echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env.production
              echo ".env.production file created."
            else
              echo "ENV_FILE_PRODUCTION secret is not set. Skipping .env.production creation."
            fi

            echo "Installing production dependencies..."
            pnpm install --prod --frozen-lockfile

            # Check if PM2 process exists, restart if it does, start if it doesn't
            if pm2 describe nextjs-portfolio-blog > /dev/null 2>&1; then
              echo "PM2 process exists. Restarting..."
              pm2 restart nextjs-portfolio-blog
            else
              echo "PM2 process doesn't exist. Starting new process..."
              pm2 start npm --name "nextjs-portfolio-blog" -- start
            fi

            # Verify deployment
            pm2 status nextjs-portfolio-blog
            echo "Deployment completed successfully."

      - name: Validate deployment health
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Wait for application to start
            sleep 10

            # Source environment
            [ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"
            [ -s "$HOME/.bashrc" ] && source "$HOME/.bashrc"

            # Check if PM2 process is running
            if ! pm2 describe nextjs-portfolio-blog | grep -q "online"; then
              echo "Error: Application is not running properly"
              pm2 logs nextjs-portfolio-blog --lines 20
              exit 1
            fi

            echo "Health check passed - Application is running successfully"

      - name: Comment PR - Deployment Successful
        if: steps.pr_number.outputs.pr_found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.pr_number.outputs.pr_number }};
            const workflow_url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `## ✅ Deployment Successful!\n\n` +
                    `The deployment for this PR has completed successfully.\n\n` +
                    `**Status:** Completed ✅\n` +
                    `**Workflow:** [View full deployment log](${workflow_url})\n` +
                    `**Completed at:** ${new Date().toISOString()}\n\n` +
                    `### Deployment Summary\n` +
                    `- ✅ Build completed\n` +
                    `- ✅ Files deployed to EC2\n` +
                    `- ✅ Application restarted\n` +
                    `- ✅ Health check passed\n\n` +
                    `Your changes are now live! 🎉`
            });

      - name: Comment PR - Deployment Failed
        if: failure() && steps.pr_number.outputs.pr_found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.pr_number.outputs.pr_number }};
            const workflow_url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `## ❌ Deployment Failed\n\n` +
                    `The deployment for this PR has failed. Please check the logs for details.\n\n` +
                    `**Status:** Failed ❌\n` +
                    `**Workflow:** [View error logs](${workflow_url})\n` +
                    `**Failed at:** ${new Date().toISOString()}\n\n` +
                    `### Next Steps\n` +
                    `1. Check the [workflow logs](${workflow_url}) for specific error details\n` +
                    `2. Fix any issues identified\n` +
                    `3. Push additional commits to retry deployment\n\n` +
                    `Please investigate and resolve the deployment issues.`
            });
